import { Package, Location, Product } from './schemas';

export const PACKAGES: Package[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 50000,
    duration: '2 hours',
    attendees: 'Up to 10 people',
    badge: 'Popular',
    color: 'purple',
    features: [
      '2-hour guided session',
      'All art materials',
      'Canvas & brushes',
      'Professional instructor',
      'Refreshments included',
    ],
  },
  {
    id: 'standard',
    name: 'Standard',
    price: 120000,
    duration: '3 hours',
    attendees: 'Up to 25 people',
    badge: 'Best Value',
    color: 'coral',
    features: [
      '3-hour guided session',
      'Premium art materials',
      'Multiple canvas options',
      '2 instructors',
      'Snacks & drinks',
      'Photo documentation',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 250000,
    duration: '4 hours',
    attendees: 'Up to 50 people',
    badge: 'Recommended',
    color: 'mint',
    features: [
      '4-hour full experience',
      'Premium art supplies',
      '3 instructors',
      'Full catering service',
      'Professional photography',
      'Certificates & art kits',
    ],
  },
];

export const LAGOS_LOCATIONS: Location[] = [
  {
    id: 'lagos-lekki',
    name: 'Lekki Studio',
    city: 'lagos',
    address: '15 Admiralty Way, Lekki Phase 1',
    hours: 'Open Daily',
    phone: '+234 123 456 7890',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&auto=format&fit=crop',
    icon: '🎨',
  },
  {
    id: 'lagos-vi',
    name: 'Victoria Island',
    city: 'lagos',
    address: '42 Adeola Odeku St, Victoria Island',
    hours: 'Mon - Sat',
    phone: '+234 123 456 7891',
    image: 'https://images.unsplash.com/photo-1572883454114-1cf0031ede2a?w=400&auto=format&fit=crop',
    icon: '🖌️',
  },
  {
    id: 'lagos-ikeja',
    name: 'Ikeja Hub',
    city: 'lagos',
    address: '28 Awolowo Way, Ikeja GRA',
    hours: 'Open Daily',
    phone: '+234 123 456 7892',
    image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=400&auto=format&fit=crop',
    icon: '🎭',
  },
  {
    id: 'lagos-surulere',
    name: 'Surulere Space',
    city: 'lagos',
    address: '65 Adeniran Ogunsanya, Surulere',
    hours: 'Tue - Sun',
    phone: '+234 123 456 7893',
    image: 'https://images.unsplash.com/photo-1567168544230-c0e8e5c88f6e?w=400&auto=format&fit=crop',
    icon: '✨',
  },
  {
    id: 'lagos-ajah',
    name: 'Ajah Gallery',
    city: 'lagos',
    address: '10 Lekki-Epe Expressway, Ajah',
    hours: 'Open Daily',
    phone: '+234 123 456 7894',
    image: 'https://images.unsplash.com/photo-1562095241-8c6714fd4178?w=400&auto=format&fit=crop',
    icon: '🌟',
  },
  {
    id: 'lagos-yaba',
    name: 'Yaba Corner',
    city: 'lagos',
    address: '23 Herbert Macaulay, Yaba',
    hours: 'Mon - Sat',
    phone: '+234 123 456 7895',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&auto=format&fit=crop',
    icon: '💫',
  },
];

export const WARRI_LOCATIONS: Location[] = [
  {
    id: 'warri-effurun',
    name: 'Effurun Studio',
    city: 'warri',
    address: '35 Effurun-Sapele Rd, Effurun',
    hours: 'Open Daily',
    phone: '+234 123 456 7896',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400&auto=format&fit=crop',
    icon: '🎨',
  },
  {
    id: 'warri-city',
    name: 'City Centre',
    city: 'warri',
    address: '18 Deco Road, Warri',
    hours: 'Mon - Sat',
    phone: '+234 123 456 7897',
    image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=400&auto=format&fit=crop',
    icon: '🖌️',
  },
  {
    id: 'warri-airport',
    name: 'Airport Hub',
    city: 'warri',
    address: '56 Airport Road, Warri',
    hours: 'Tue - Sun',
    phone: '+234 123 456 7898',
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400&auto=format&fit=crop',
    icon: '🎭',
  },
  {
    id: 'warri-pti',
    name: 'PTI Gallery',
    city: 'warri',
    address: '12 PTI Road, Warri',
    hours: 'Open Daily',
    phone: '+234 123 456 7899',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&auto=format&fit=crop',
    icon: '✨',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'beginner-kit',
    name: "Beginner's Complete Kit",
    price: 15000,
    description: 'Everything you need to start',
    category: 'kits',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop',
  },
  {
    id: 'pro-brushes',
    name: 'Professional Brush Set',
    price: 8500,
    description: '12 premium brushes',
    category: 'brushes',
    image: 'https://images.unsplash.com/photo-1572364404944-a7b29f406f12?w=600&auto=format&fit=crop',
  },
  {
    id: 'acrylic-set',
    name: 'Acrylic Paint Set',
    price: 12000,
    description: '24 vibrant colors',
    category: 'paints',
    image: 'https://images.unsplash.com/photo-1596548438137-d51ea5c83711?w=600&auto=format&fit=crop',
  },
  {
    id: 'canvas-pack',
    name: 'Canvas Value Pack',
    price: 10000,
    description: '5 pre-stretched canvases',
    category: 'canvases',
    image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=600&auto=format&fit=crop',
  },
  {
    id: 'watercolor-deluxe',
    name: 'Watercolor Deluxe Set',
    price: 18000,
    description: 'Professional grade',
    category: 'paints',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&auto=format&fit=crop',
  },
  {
    id: 'accessories',
    name: 'Essential Accessories',
    price: 6500,
    description: 'Palette, knives & more',
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600&auto=format&fit=crop',
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'premium-kit',
    name: 'Premium Starter Kit',
    price: 28000,
    description: 'Perfect for anyone starting their painting journey',
    category: 'kits',
    image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop',
    features: [
      '12 acrylic paint tubes (50ml each)',
      '8 professional brushes (various sizes)',
      '3 pre-stretched canvases (16x20")',
      'Wooden palette with thumb hole',
      'Canvas carrying case',
      'Instructional guide included',
    ],
  },
  {
    id: 'professional-set',
    name: 'Professional Artist Set',
    price: 65000,
    description: 'For serious artists who demand the best',
    category: 'kits',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop',
    features: [
      '24 artist-grade acrylic paints',
      '15 premium brush collection',
      '5 gallery-wrapped canvases',
      'Professional palette with mixing wells',
      'Portable easel included',
      'Storage case with compartments',
    ],
  },
  {
    id: 'kids-kit',
    name: 'Kids Creative Kit',
    price: 18500,
    description: 'Safe, non-toxic materials for young artists',
    category: 'kits',
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&auto=format&fit=crop',
    features: [
      '12 washable acrylic paints',
      '6 child-safe brushes',
      '3 canvas boards (11x14")',
      'Plastic palette easy to clean',
      'Protective art smock',
      'Fun activity guide',
    ],
  },
];